
services:
  hadoop:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: hadoop
    environment:
      CLUSTER_NAME: test-cluster
      CORE_CONF_fs_defaultFS: hdfs://hadoop:9000
    ports:
      - "9870:9870"   # HDFS web UI
      - "9000:9000"   # HDFS namenode
    networks:
      - bigdata

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    depends_on:
      - hadoop
    environment:
      CORE_CONF_fs_defaultFS: hdfs://hadoop:9000
      HDFS_CONF_dfs_replication: 1
      NAMENODE_HOST: hadoop
    networks:
      - bigdata

  spark:
    image: bitnami/spark:latest
    container_name: spark
    depends_on:
      - hadoop
    environment:
      SPARK_MODE: master
    ports:
      - "8080:8080"   # Spark master web UI
    networks:
      - bigdata

  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"   # Jupyter web UI
    environment:
      PYSPARK_PYTHON: python3
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - bigdata

networks:
  bigdata:
    driver: bridge
